name: Deploy to GitHub Pages

on:
  push:
  pull_request:

jobs:
  build_and_upload:
    name: Build pages and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
          check-latest: true
          cache-dependency-path: |
            scripts/asmdb/go.sum

      - name: Install dependencies
        run: yarn install --immutable
      - name: Build AWLY helpers
        run: yarn build-helpers
      - name: Build website
        run: yarn build

      - name: Upload pages artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/'
          name: 'gh-pages-${{github.sha}}'

      - name: Upload pages artifacts
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          path: './build/'
          name: 'pages-${{github.sha}}'

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency:
      group: "pages"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    needs: build_and_upload
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: 'gh-pages-${{github.sha}}'
