name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'
          check-latest: true
          cache-dependency-path: |
            scripts/asmdb/go.sum

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build AWLY helpers
        run: yarn build-helpers
      - name: Build AWLY plugins
        run: yarn make-plugins
      - name: Test build website
        run: yarn build
